# generated by datamodel-codegen:
#   filename:  oci_annotations.yaml
#   timestamp: 2026-08-24T14:15:23+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class OciAnnotations(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    org_opencontainers_image_title: Annotated[
        str, Field(alias="org.opencontainers.image.title")
    ]
    """
    The `org.opencontainers.image.title` property

    """
    org_opencontainers_image_description: Annotated[
        str, Field(alias="org.opencontainers.image.description")
    ]
    """
    The `org.opencontainers.image.description` property

    """
    org_opencontainers_image_version: Annotated[
        str, Field(alias="org.opencontainers.image.version")
    ]
    """
    The `org.opencontainers.image.version` property

    """
    org_opencontainers_image_source: Annotated[
        str | None, Field(alias="org.opencontainers.image.source")
    ] = None
    """
    The `org.opencontainers.image.source` property

    """
    org_opencontainers_image_revision: Annotated[
        str | None, Field(alias="org.opencontainers.image.revision")
    ] = None
    """
    The `org.opencontainers.image.revision` property

    """
    org_opencontainers_image_licenses: Annotated[
        str, Field(alias="org.opencontainers.image.licenses")
    ]
    """
    The `org.opencontainers.image.licenses` property

    """
    org_cwl_entrypoint: Annotated[str, Field(alias="org.cwl.entrypoint")]
    """
    The `org.cwl.entrypoint` property

    """
    org_cwl_spec: Annotated[str | None, Field(alias="org.cwl.spec")] = None
    """
    The `org.cwl.spec` property

    """
    org_cwl_type: Annotated[str, Field(alias="org.cwl.type")]
    """
    The `org.cwl.type` property

    """


class Model(RootModel[OciAnnotations]):
    root: OciAnnotations
